Don't use system libclang, because there's no such thing on mac and it could be causing my ycmd failures in emacs on linux. Don't set sh-indentation in emacs.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -86,8 +86,7 @@ git pull --rebase || die "Cannot update ycmd"
 if [ "$hash" != "`git log -n 1 --format=%h`" ]; then
   git submodule update --init --recursive \
     || die "Cannot update ycmd dependencies"
-  ./build.py --clang-completer --system-libclang --gocode-completer \
-    || die "Cannot build ycmd"
+  ./build.py --clang-completer --gocode-completer || die "Cannot build ycmd"
 fi
 popd || die "Cannot return from ycmd dir"
 
