Clean up python packages in `install --force`.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -144,6 +144,7 @@ PYTHON_APPS="yapf"
 for app in $PYTHON_APPS; do
   which $app >& /dev/null
   if [ $? -ne 0 -o $FORCE -eq 1 ]; then
+    rm -rvf $HOME/python/${app}* || die "Cannot clean up $app"
     pip install --target=$HOME/python $app || die "Cannot install $app"
     echo -e "#!/bin/bash\nexec python \$HOME/python/$app" > ~/python/bin/$app \
       || die "Cannot create $app launcher"
