Set mac linker manually, because sourcing common.sh does not export the aliases for some reason.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -88,12 +88,15 @@ if [ ! -e ycmd/ycm_core.so ]; then
   popd || die "Cannot return from ycmd dir"
 fi
 
+LINKER=ln
+$LINKER --version > /dev/null 2>&1 || LINKER=gln
+
 for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
   env-cros.sh env-gn.sh env-lsan.sh fluxbox/apps fluxbox/menu fluxbox/startup \
   fluxbox/init fluxbox/keys fluxbox/windowmenu screenrc tmux.conf vimrc \
   vim/autoload/plug.vim zshrc Xresources bashrc bash_profile ycmd; do
   mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
-  ln -sfvT ~/.dotfiles/$file ~/.$file || die "Cannot link $file to home dir"
+  $LINKER -sfvT ~/.dotfiles/$file ~/.$file || die "Cannot link $file to home dir"
 done
 
 emacs -nw -f install-my-packages --kill || die "Cannot install emacs packages"
