Install npm modules without sudo

diff --git a/install b/install
--- a/install
+++ b/install
@@ -51,36 +51,24 @@ git config --global --replace-all user.name "Rouslan Solomakhin" \
 
 git submodule update --init --recursive || die "Cannot update submodules"
 
-CONFIGS="cvsignore tmux.conf vim/bundle bashrc bash_profile"
-
 mkdir -pv $HOME/software/bin || die "Cannot create $HOME/software/bin dir"
+mkdir -pv ~/.vim/swap || die "Cannot create the vim swap dir"
+mkdir -pv ~/.vim/autoload || die "Cannot create autoload dir"
+
+export GOPATH=$HOME/go
+export PATH=$GOPATH/bin:$PATH
+export PATH=$HOME/software/bin:$PATH \
+  || die "Cannot add $HOME/software/bin to the path"
+
+CONFIGS="cvsignore tmux.conf vim/bundle bashrc bash_profile"
+PROGS="npm cmake curl"
 which apt-get > /dev/null
 if [ $? -eq 0 ]; then
   CONFIGS="$CONFIGS fluxbox/apps fluxbox/menu fluxbox/startup fluxbox/init fluxbox/keys fluxbox/windowmenu Xresources"
-
-  if [ ! `which go` ]; then
-    sudo apt-get install golang || die "Cannot install go"
-  fi
-  if [ ! `which npm` ]; then
-    sudo apt-get install npm || die "Cannot install node package manager"
-  fi
-  if [ ! `which fluxbox` ]; then
-    sudo apt-get install fluxbox || die "Cannot install fluxbox window manager"
-  fi
-  if [ ! `which curl` ]; then
-    sudo apt-get install curl || die "Cannot install curl downloader"
-  fi
-  if [ ! `which cmake` -o ! `which python-config` ]; then
-    sudo apt-get install cmake python-dev \
-      || die "Cannot install YCM deps"
-  fi
+  PROGS="$PROGS golang fluxbox python-dev"
+  sudo apt-get isntall $PROGS || die "Cannot install programs"
   ln -svfT /usr/bin/nodejs $HOME/software/bin/node \
     || die "Cannot link node to nodejs"
-  sudo npm install -g eslint || die "Cannot install eslint"
-  sudo npm install -g eslint-config-google \
-    || die "Cannot install Google config for eslint"
-  sudo npm install -g csslint || die "Cannot install csslint"
-  sudo npm install -g tern || die "Cannot install tern"
 else
   if [ ! -e $HOME/software/bin/brew ]; then
     pushd $HOME/software || die "Cannot change dir to $HOME/software"
@@ -92,24 +80,9 @@ else
     brew update || die "Cannot update homebrew formulae"
     brew upgrade --all || die "Cannot upgrade all homebrew packages"
   fi
-  export PATH=$HOME/software/bin:$PATH \
-    || die "Cannot add $HOME/software/bin to the path"
-  brew install go || die "Cannot install go"
-  brew install npm || die "Cannot install node package manager"
-  brew install cmake || die "Cannot install cmake for YCM"
-  brew install curl || die "Cannot install curl downloader"
-  brew install bash vim emacs coreutils clang-format tmux \
-    || die "Cannot install updated tools"
-  npm install -g eslint || die "Cannot install eslint"
-  npm install -g eslint-config-google \
-    || die "Cannot install Google config for eslint"
-  npm install -g csslint || die "Cannot install csslint"
-  npm install -g tern || die "Cannot install tern"
+  PROGS="$PROGS go bash vim coreutils clang-format tmux"
+  brew install $PROGS || die "Cannot install programs"
 fi
-
-export GOPATH=$HOME/go
-export PATH=$GOPATH/bin:$PATH
-go get github.com/nsf/gocode || die "Cannot get gocode package for go"
 
 LINKER=ln
 $LINKER --version >& /dev/null || LINKER=gln
@@ -118,10 +91,16 @@ for file in $CONFIGS; do
   $LINKER -sfvT $PWD/$file ~/.$file || die "Cannot link $file to home dir"
 done
 
-mkdir -p ~/.vim/swap || die "Cannot create the vim swap dir"
-mkdir -p ~/.vim/autoload || die "Cannot create autoload dir"
-curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim \
-  die "Cannot download vim-pathogen"
+go get github.com/nsf/gocode || die "Cannot get gocode package for go"
+
+NODE_MODULES="eslint eslint-config-google csslint tern"
+npm install --global --prefix=$HOME/software $NODE_MODULES \
+  || die "Cannot install NODE MODULES"
+
+if [ ! -e ~/.vim/autoload/pathogen.vim ]; then
+  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim \
+    || die "Cannot download vim-pathogen"
+fi
 
 pushd vim/bundle/YouCompleteMe || die "Cannot change dir"
 ./install.py --clang-completer --gocode-completer --tern-completer \
