Add yapf

diff --git a/install b/install
--- a/install
+++ b/install
@@ -63,6 +63,7 @@ git config --global --replace-all user.name "Rouslan Solomakhin" \
 git submodule update --init --recursive || die "Cannot update submodules"
 
 mkdir -pv ~/node/bin || die "Cannot create ~/node/bin dir"
+mkdir -pv ~/python/bin || die "Cannot create ~/python/bin dir"
 mkdir -pv ~/.vim/swap || die "Cannot create the vim swap dir"
 mkdir -pv ~/.vim/spell || die "Cannot create the vim spell dir"
 mkdir -pv ~/.vim/autoload || die "Cannot create vim autoload dir"
@@ -70,6 +71,7 @@ mkdir -pv ~/.vim/autoload || die "Cannot create vim autoload dir"
 export GOPATH=$HOME/go || die "Cannot set the go path"
 export PATH=$GOPATH/bin:$PATH || die "Cannot add ~/go/bin to the path"
 export PATH=$HOME/node/bin:$PATH || die "Cannot add ~/node/bin to the path"
+export PATH=$HOME/python/bin:$PATH || die "Cannot add ~/python/bin to the path"
 
 CONFIGS="cvsignore tmux.conf vim/bundle bashrc bash_profile vimrc tern-config"
 PROGS="cmake npm"
@@ -127,6 +129,18 @@ for mod in $NODE_MODULES; do
   fi
 done
 
+PYTHONPATH=$HOME/python:$PYTHONPATH
+PYTHON_APPS="yapf"
+for app in $PYTHON_APPS; do
+  which $app >& /dev/null
+  if [ $? -ne 0 -o $FORCE -eq 1 ]; then
+    pip install --target=$HOME/python $app || die "Cannot install $app"
+    echo -e "#!/bin/bash\nexec python \$HOME/python/$app" > ~/python/bin/$app \
+      || die "Cannot create $app launcher"
+    chmod +x ~/python/bin/$app || die "Cannot make $app launcher executable"
+  fi
+done
+
 if [ ! -e ~/.vim/autoload/pathogen.vim -o $FORCE -eq 1 ]; then
   echo "Installing vim-pathogen"
   curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim \
@@ -144,16 +158,16 @@ fi
 if [ ! -e vim/bundle/mojom -o $FORCE -eq 1 ]; then
   rm -rfv vim/bundle/mojom || die "Cannot clear the old mojom directory"
   if [ -e ~/chrome/src/tools/vim/mojom ]; then
-    cp -av ~/chrome/src/tools/vim/mojom vim/bundle/mojom || \
-      die "Cannot copy over the mojom vim syntax config"
+    cp -av ~/chrome/src/tools/vim/mojom vim/bundle/mojom \
+      || die "Cannot copy over the mojom vim syntax config"
   fi
 fi
 
 if [ ! -e vim/bundle/gn -o $FORCE -eq 1 ]; then
   rm -rfv vim/bundle/gn || die "Cannot clear the old gn directory"
   if [ -e ~/chrome/src/tools/gn/misc/vim ]; then
-    cp -av ~/chrome/src/tools/gn/misc/vim  vim/bundle/gn || \
-      die "Cannot copy over the gn vim syntax config"
+    cp -av ~/chrome/src/tools/gn/misc/vim  vim/bundle/gn \
+      || die "Cannot copy over the gn vim syntax config"
   fi
 fi
 
