Fix typo

diff --git a/install b/install
--- a/install
+++ b/install
@@ -66,7 +66,7 @@ which apt-get > /dev/null
 if [ $? -eq 0 ]; then
   CONFIGS="$CONFIGS fluxbox/apps fluxbox/menu fluxbox/startup fluxbox/init fluxbox/keys fluxbox/windowmenu Xresources"
   PROGS="$PROGS golang fluxbox python-dev"
-  sudo apt-get isntall $PROGS || die "Cannot install programs"
+  sudo apt-get install $PROGS || die "Cannot install programs"
   ln -svfT /usr/bin/nodejs $HOME/software/bin/node \
     || die "Cannot link node to nodejs"
 else
