Link and compile company mode.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -91,18 +91,18 @@ for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
   env-cros.sh env-gn.sh env-lsan.sh fluxbox/apps fluxbox/menu fluxbox/startup \
   fluxbox/init fluxbox/keys fluxbox/windowmenu screenrc tmux.conf vim/vimrc \
   vim/autoload/plug.vim zshrc Xresources bashrc bash_profile \
-  emacs.d/lisp/clang-format/clang-format.el \
+  emacs.d/lisp/clang-format/clang-format.el emacs.d/lisp/company-mode/*.el \
   emacs.d/lisp/styleguide/google-c-style.el; do
   mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
   $LINKER -sfvT $PWD/$file ~/.$file || die "Cannot link $file to home dir"
+  if [[ $file == *.el ]]; then
+    emacs -batch -f batch-byte-compile ~/.$file \
+      || die "Cannot compile lisp file $file"
+  elif ls ~/.$file/*.el &> /dev/null; then
+    emacs -batch -f batch-byte-compile ~/.$file/*.el \
+      || die "Cannot compile lisp files in $file dir"
+  fi
 done
 
 vim -c ":PlugUpgrade" -c ":PlugInstall" -c ":PlugUpdate" -c ":qa" \
   || die "Cannot install vim plugins"
-
-emacs -batch -f batch-byte-compile $HOME/.emacs.d/*.el \
-  || die "Cannot compile emacs init file"
-emacs -batch -f batch-byte-compile $HOME/.emacs.d/lisp/clang-format/*.el \
-  || die "Cannot compile clang-format emacs library"
-emacs -batch -f batch-byte-compile $HOME/.emacs.d/lisp/styleguide/*.el \
-  || die "Cannot compile styleguide emacs library"
