Always run from install script's dir.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,8 +16,11 @@
 
 die() {
   echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+  popd
   exit 1
 }
+
+pushd $(dirname ${BASH_SOURCE[0]})
 
 git config user.email "rouslan.solomakhin@gmail.com" \
   || die "Cannot set git user email for this repository"
@@ -89,15 +92,17 @@ if [ ! -e ycmd/ycm_core.so ]; then
 fi
 
 LINKER=ln
-$LINKER --version > /dev/null 2>&1 || LINKER=gln
+$LINKER --version >& /dev/null || LINKER=gln
 
 for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
   env-cros.sh env-gn.sh env-lsan.sh fluxbox/apps fluxbox/menu fluxbox/startup \
   fluxbox/init fluxbox/keys fluxbox/windowmenu screenrc tmux.conf vimrc \
   vim/autoload/plug.vim zshrc Xresources bashrc bash_profile ycmd; do
   mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
-  $LINKER -sfvT $file ~/.$file || die "Cannot link $file to home dir"
+  $LINKER -sfvT $PWD/$file ~/.$file || die "Cannot link $file to home dir"
 done
 
 emacs -nw -f install-my-packages --kill || die "Cannot install emacs packages"
 vim -c ":PlugInstall" -c ":qa" || die "Cannot install vim plugins"
+
+popd
