Preserve existing GYP_DEFINES. Alias the newer ln.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -19,16 +19,6 @@ die() {
   exit 1
 }
 
-for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
-  env-cros.sh env-gn.sh env-lsan.sh fluxbox/apps fluxbox/menu fluxbox/startup \
-  fluxbox/init fluxbox/keys fluxbox/windowmenu screenrc tmux.conf vimrc \
-  vim/autoload/plug.vim zshrc Xresources bashrc bash_profile ycmd; do
-  mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
-  ln -sfvT ~/.dotfiles/$file ~/.$file \
-    || gln -sfvT ~/.dotfiles/$file ~/.$file \
-    || die "Cannot link $file to home dir"
-done
-
 git config user.email "rouslan.solomakhin@gmail.com" \
   || die "Cannot set git user email for this repository"
 git config --global --get user.email \
@@ -93,6 +83,17 @@ if [ ! -e ycmd/ycm_core.so ]; then
   ./build.py --clang-completer --gocode-completer || die "Cannot build ycmd"
   popd || die "Cannot return from ycmd dir"
 fi
+
+# Setup path and aliases for running 'ln' on mac.
+source common.sh
+
+for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
+  env-cros.sh env-gn.sh env-lsan.sh fluxbox/apps fluxbox/menu fluxbox/startup \
+  fluxbox/init fluxbox/keys fluxbox/windowmenu screenrc tmux.conf vimrc \
+  vim/autoload/plug.vim zshrc Xresources bashrc bash_profile ycmd; do
+  mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
+  ln -sfvT ~/.dotfiles/$file ~/.$file || die "Cannot link $file to home dir"
+done
 
 emacs -nw -f install-my-packages --kill || die "Cannot install emacs packages"
 vim -c ":PlugInstall" -c ":qa" || die "Cannot install vim plugins"
