Link node to nodejs only on Linux.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -58,6 +58,8 @@ if [ $? -eq 0 ]; then
   sudo apt-get install npm || die "Cannot install node package manager"
   sudo apt-get install build-essential cmake python-dev \
     || die "Cannot install YCM deps"
+  ln -svfT /usr/bin/nodejs ~/software/bin/node \
+    || die "Cannot link node to nodejs"
 else
   if [ ! -e $HOME/software/bin/brew ]; then
     mkdir -p $HOME/software || die "Cannot create $HOME/software dir"
@@ -91,8 +93,6 @@ for file in common.sh cvsignore emacs.d/init.el env-android.sh env-clang.sh \
   mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
   $LINKER -sfvT $PWD/$file ~/.$file || die "Cannot link $file to home dir"
 done
-
-$LINKER -svfT /usr/bin/nodejs ~/software/bin/node
 
 vim -c ":PlugInstall" -c ":qa" || die "Cannot install vim plugins"
 $LINKER -sfvT ~/.vim/plugged/YouCompleteMe/third_party/ycmd ~/.ycmd \
