Don't fail install if some packages are not available

diff --git a/install b/install
--- a/install
+++ b/install
@@ -32,6 +32,10 @@ die() {
   exit 1
 }
 
+warn() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+}
+
 pushd $(dirname ${BASH_SOURCE[0]}) || die "Cannot go into ${BASH_SOURCE[0]} dir"
 
 git config user.email "rouslan.solomakhin@gmail.com" \
@@ -88,7 +92,7 @@ if [ $? -eq 0 ]; then
   for prog in $PROGS; do
     which $prog >& /dev/null
     if [ $? -ne 0 -o $FORCE -eq 1 ]; then
-      sudo apt-get install $PROGS || die "Cannot install $prog"
+      sudo apt-get install $prog || warn "Cannot install $prog"
     fi
   done
   which inotifywait >& /dev/null
