Move brew, don't install coreutils, add --force flag.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,9 +14,15 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+ARGS=$@
+
 FORCE=0
-if [ "$@" == "--force" ]; then
+if [ "$ARGS" == "--force" ]; then
   FORCE=1
+  echo "Forcing builds and installs"
+elif [ -n "$ARGS" ]; then
+  echo "Usage: ./install [--force]"
+  exit 1
 fi
 
 die() {
@@ -56,66 +62,87 @@ git config --global --replace-all user.name "Rouslan Solomakhin" \
 
 git submodule update --init --recursive || die "Cannot update submodules"
 
-mkdir -pv $HOME/software/bin || die "Cannot create $HOME/software/bin dir"
+mkdir -pv ~/software/bin || die "Cannot create $HOME/software/bin dir"
 mkdir -pv ~/.vim/swap || die "Cannot create the vim swap dir"
-mkdir -pv ~/.vim/autoload || die "Cannot create autoload dir"
+mkdir -pv ~/.vim/autoload || die "Cannot create vim autoload dir"
 
-export GOPATH=$HOME/go
-export PATH=$GOPATH/bin:$PATH
+export GOPATH=$HOME/go || die "Cannot set the go path"
+export PATH=$GOPATH/bin:$PATH || die "Cannot add $GOPATH/bin to the path"
 export PATH=$HOME/software/bin:$PATH \
   || die "Cannot add $HOME/software/bin to the path"
 
 CONFIGS="cvsignore tmux.conf vim/bundle bashrc bash_profile"
-PROGS="cmake curl npm"
-which apt-get > /dev/null
-if [ $? -eq 0 ]; then
+PROGS="cmake npm"
+
+if [ `which apt-get` ]; then
   CONFIGS="$CONFIGS fluxbox/apps fluxbox/menu fluxbox/startup fluxbox/init fluxbox/keys fluxbox/windowmenu Xresources"
-  PROGS="$PROGS golang fluxbox python-dev"
-  sudo apt-get install $PROGS || die "Cannot install programs"
-  ln -svfT /usr/bin/nodejs $HOME/software/bin/node \
+  PROGS="$PROGS curl golang fluxbox python-dev"
+  for prog in $PROGS; do
+    if [ ! `which $prog` -o $FORCE -eq 1 ]; then
+      sudo apt-get install $PROGS || die "Cannot install $prog"
+    fi
+  done
+  ln -svf /usr/bin/nodejs ~/software/bin/node \
     || die "Cannot link node to nodejs"
 else
-  if [ ! -e $HOME/software/bin/brew ]; then
-    pushd $HOME/software || die "Cannot change dir to $HOME/software"
-    curl -L https://github.com/Homebrew/homebrew/tarball/master \
-      | tar xz --strip 1 \
+  export PATH=$HOME/homebrew/bin:$PATH \
+    || die "Cannot add $HOME/homebrew/bin to the path"
+  which brew >& /dev/null
+  if [ $? -ne 0 -o $FORCE -eq 1 ]; then
+    echo "Installing homebrew"
+    mkdir -pv ~/homebrew || die "Cannot create $HOME/homebrew dir"
+    curl -L https://github.com/Homebrew/brew/tarball/master \
+      | tar xz --strip 1 -C ~/homebrew \
       || die "Cannot download homebrew"
-    popd || die "Cannot return to previous dir"
   else
     brew update || die "Cannot update homebrew formulae"
     brew upgrade --all || die "Cannot upgrade all homebrew packages"
   fi
-  PROGS="$PROGS go bash vim coreutils clang-format tmux"
-  brew install $PROGS || die "Cannot install programs"
+  PROGS="$PROGS go bash vim clang-format tmux"
+  for prog in $PROGS; do
+    which $prog >& /dev/null
+    if [ $? -ne 0 -o $FORCE -eq 1 ]; then
+      brew install $PROGS || die "Cannot install $prog"
+    fi
+  done
 fi
 
-LINKER=ln
-$LINKER --version >& /dev/null || LINKER=gln
 for file in $CONFIGS; do
   mkdir -pv ~/.`dirname $file` || die "Cannot create the dir for $file"
-  $LINKER -sfvT $PWD/$file ~/.$file || die "Cannot link $file to home dir"
+  [ -e ~/.$file ] || ln -sfv $PWD/$file ~/.$file \
+    || die "Cannot link $file to home dir"
 done
 
-go get github.com/nsf/gocode || die "Cannot get gocode package for go"
+if [ ! -e ~/go/bin/gocode -o $FORCE -eq 1 ]; then
+  go get github.com/nsf/gocode || die "Cannot get gocode package for go"
+fi
 
 NODE_MODULES="eslint eslint-config-google csslint tern"
-npm install --global --prefix=$HOME/software $NODE_MODULES \
-  || die "Cannot install NODE MODULES"
+for mod in $NODE_MODULES; do
+  if [ ! -e ~/software/lib/node_modules/$mod -o $FORCE -eq 1 ]; then
+    npm install --global --prefix=$HOME/software $mod \
+      || die "Cannot install $mod"
+  fi
+done
 
-if [ ! -e ~/.vim/autoload/pathogen.vim ]; then
+if [ ! -e ~/.vim/autoload/pathogen.vim -o $FORCE -eq 1 ]; then
+  echo "Installing vim-pathogen"
   curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim \
     || die "Cannot download vim-pathogen"
 fi
 
 YCM_OUTPUT=vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so
-if [ ! -e $YCM_OUTPUT -a ! $FORCE ]; then
+if [ ! -e $YCM_OUTPUT -o $FORCE -eq 1 ]; then
   pushd vim/bundle/YouCompleteMe || die "Cannot change dir"
   ./install.py --clang-completer --gocode-completer --tern-completer \
     || die "Cannot install YCM"
   popd || die "Cannot go back"
 fi
 
-$LINKER -sfvT `pwd`/vim/bundle/fzf ~/.fzf
-pushd ~/.fzf || die "Cannot go to fzf dir"
-./install --all || die "Cannot install fzf"
-popd || die "Cannot go back"
+[ -e ~/.fzf ] || ln -sfv $PWD/vim/bundle/fzf ~/.fzf \
+  || die "Cannot link $HOME/.fzf"
+if [ ! -e ~/.fzf/bin/fzf -o $FORCE -eq 1 ]; then
+  pushd ~/.fzf || die "Cannot go to fzf dir"
+  ./install --all || die "Cannot install fzf"
+  popd || die "Cannot go back"
+fi
