Install emacs24-nox.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -55,6 +55,7 @@ git submodule update --init --recursive || die "Cannot update submodules"
 mkdir -pv $HOME/software/bin || die "Cannot create $HOME/software/bin dir"
 which apt-get > /dev/null
 if [ $? -eq 0 ]; then
+  sudo apt-get install emacs24-nox || die "Canot install emacs"
   sudo apt-get install golang || die "Cannot install go"
   sudo apt-get install npm || die "Cannot install node package manager"
   sudo apt-get install build-essential cmake python-dev \
