Suppress 'not a terminal' warning

diff --git a/install b/install
--- a/install
+++ b/install
@@ -197,5 +197,6 @@ if [ ! -e ~/.fzf/bin/fzf -o $FORCE -eq 1 ]; then
 fi
 
 for dir in vim/bundle/*/doc; do
-  vim -u NONE -c "helptags $dir" -c q || die "Cannot install vim docs from $dir"
+  vim --not-a-term -u NONE -c "helptags $dir" -c q \
+    || die "Cannot install vim docs from $dir"
 done
