Clean up

diff --git a/install b/install
--- a/install
+++ b/install
@@ -66,28 +66,25 @@ git config --global push.default simple || die "Cannot set simple push"
 git submodule update --init --recursive || die "Cannot update submodules"
 
 mkdir -pv ~/node/bin || die "Cannot create ~/node/bin dir"
-mkdir -pv ~/python/bin || die "Cannot create ~/python/bin dir"
 mkdir -pv ~/.vim/swap || die "Cannot create the vim swap dir"
 mkdir -pv ~/.vim/spell || die "Cannot create the vim spell dir"
 mkdir -pv ~/.vim/autoload || die "Cannot create vim autoload dir"
 mkdir -pv ~/software/bin || die "Cannot create the software dir"
-mkdir -pv ~/android-sdk || die "Cannot create the android-sdk dir"
-
-export GOPATH=$HOME/go || die "Cannot set the go path"
-export PATH=$GOPATH/bin:$PATH || die "Cannot add ~/go/bin to the path"
-export PATH=$HOME/node/bin:$PATH || die "Cannot add ~/node/bin to the path"
-export PATH=$HOME/python/bin:$PATH || die "Cannot add ~/python/bin to the path"
-export PATH=$HOME/.rvm/bin:$PATH || die "Cannot add ~/.rvm/bin to the path"
-export PATH=$HOME/software/bin:$PATH \
-  || die "Cannot add ~/software/bin to the path"
 
 CONFIGS="cvsignore tmux.conf vim/bundle bashrc bash_profile vimrc tern-config emacs eslintrc"
 PROGS="cmake tmux"
 
 which apt-get >& /dev/null
 if [ $? -eq 0 ]; then
+  # https://nodejs.org/en/download/current/
+  NODEJS_VER=7.9.0
+  # https://www.ruby-lang.org/en/downloads/
+  RUBY_VER=2.4.1
+  # https://cloud.google.com/sdk/docs/quickstart-linux
+  GOOGLE_CLOUD_SDK_VER=153.0.0
+
   CONFIGS="$CONFIGS fluxbox/apps fluxbox/menu fluxbox/startup fluxbox/init fluxbox/keys fluxbox/windowmenu Xresources config/pulse/client.conf"
-  PROGS="$PROGS curl golang fluxbox python-dev gnome-screensaver gnome-screenshot gstreamer1.0-libav"
+  PROGS="$PROGS curl golang-go fluxbox python-dev gnome-screensaver gnome-screenshot gstreamer1.0-libav android-studio-canary"
   for prog in $PROGS; do
     which $prog >& /dev/null
     if [ $? -ne 0 -o $FORCE -eq 1 ]; then
@@ -100,8 +97,13 @@ if [ $? -eq 0 ]; then
   fi
   if [ ! -f ~/node/bin/node -o $FORCE -eq 1 ]; then
     echo "Downloading nodejs"
-    curl https://nodejs.org/dist/v7.3.0/node-v7.3.0-linux-x64.tar.xz \
+    curl https://nodejs.org/dist/v${NODEJS_VER}/node-v${NODEJS_VER}-linux-x64.tar.xz \
       | tar xJ --strip 1 -C ~/node || die "Cannot download nodejs"
+  fi
+  if [ ! -f ~/google-cloud-sdk/bin/gcloud -o $FORCE -eq 1 ]; then
+    echo "Downloading Google cloud SDK"
+    curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VER}-linux-x86_64.tar.gz \
+      | tar xz -C ~ || die "Cannot download Google cloud SDK"
   fi
   if [ ! -f ~/.rvm/bin/rvm -o $FORCE -eq 1 ]; then
     gpg --keyserver hkp://keys.gnupg.net --recv-keys \
@@ -115,31 +117,9 @@ if [ $? -eq 0 ]; then
     gpg --verify /tmp/rvm-installer.asc || die "Rvm signature does not match"
     bash /tmp/rvm-installer stable || die "Cannot install rvm"
   fi
-  if [ ! -f ~/google-cloud-sdk/bin/gcloud -o $FORCE -eq 1 ]; then
-    echo "Downloading Google cloud SDK"
-    curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-139.0.1-linux-x86_64.tar.gz \
-      | tar xz -C ~ || die "Cannot download Google cloud SDK"
-  fi
-  if [ ! -f ~/android-sdk/tools/android -o $FORCE -eq 1 ]; then
-    echo "Downloading Android SDK"
-    curl -LSso /tmp/android-sdk.zip \
-      https://dl.google.com/android/repository/tools_r25.2.3-linux.zip \
-      || die "Cannot download Android SDK"
-    pushd ~/android-sdk || die "Cannot change directory to Android SDK"
-    unzip /tmp/android-sdk.zip || die "Cannot unzip Android SDK"
-    popd || die "Cannot go back in directory stack"
-  fi
-  if [ ! -f ~/android-studio/bin/studio.sh -o $FORCE -eq 1 ]; then
-    echo "Downloading Android Studio"
-    curl -LSso /tmp/android-studio.zip \
-      https://dl.google.com/dl/android/studio/ide-zips/2.2.3.0/android-studio-ide-145.3537739-linux.zip \
-      || die "Cannot download Android Studio"
-    pushd ~ || die "Cannot change directory to home dir"
-    unzip /tmp/android-studio.zip || die "Cannot unzip Android Studio"
-    popd || die "Cannot go back in directory stack"
-  fi
-  if [ ! -f ~/.rvm/rubies/ruby-2.3.3/bin/ruby -o $FORCE -eq 1 ]; then
-    rvm install 2.3 || die "Cannot install ruby"
+  if [ ! -f ~/.rvm/rubies/ruby-${RUBY_VER}/bin/ruby -o $FORCE -eq 1 ]; then
+    export PATH=$HOME/.rvm/bin:$PATH || die "Cannot add ~/.rvm/bin to the path"
+    rvm install ${RUBY_VER} || die "Cannot install ruby"
   fi
   if [ ! -e ~/.Xresources-hybrid -o $FORCE -eq 1 ]; then
     curl -LSso ~/.Xresources-hybrid \
@@ -185,6 +165,7 @@ done
 rm -rfv ~/.profile || die "Cannot clean up the .profile file"
 
 if [ $CYGWIN -eq 0 ]; then
+  export PATH=$HOME/node/bin:$PATH || die "Cannot add ~/node/bin to the path"
   NODE_MODULES="eslint eslint-config-google csslint typescript tern gulp bower js-beautify"
   for mod in $NODE_MODULES; do
     if [ ! -e ~/node/lib/node_modules/$mod -o $FORCE -eq 1 ]; then
@@ -199,14 +180,4 @@ if [ ! -e ~/.vim/autoload/plug.vim -o $FORCE -eq 1 ]; then
   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
     || die "Cannot download vim-plug"
-fi
-
-if [ $CYGWIN -eq 0 ]; then
-  YCM_OUTPUT=third_party/ycmd/ycm_core.so
-  if [ ! -e $YCM_OUTPUT -o $FORCE -eq 1 ]; then
-    pushd third_party/ycmd || die "Cannot change dir to ycmd for emacs and atom"
-    ./build.py --clang-completer --gocode-completer --tern-completer \
-      || die "Cannot build ycmd for emacs and atom"
-    popd || die "Cannot go back from ycmd dir for emacs and atom"
-  fi
 fi
